'use client'

import Link from 'next/link'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'

export default function SignUpPage() {
  const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); const { error } = await createClient().auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback`, data: { display_name: displayName.trim() } } }); setBusy(false); if (error) setError(error.message.toLowerCase().includes('password') ? 'Choose a stronger password with at least 6 characters.' : error.status === 429 ? 'Too many attempts. Please try again later.' : 'We could not create your account. Check your details and try again.'); else setSent(true) }
  if (sent) return <main className="flex min-h-screen items-center justify-center bg-background px-5 py-12"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-7 text-center"><p className="eyebrow">Almost there</p><h1 className="font-serif text-4xl font-bold">Check your inbox</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">We sent a confirmation link to your email. Confirm it to activate your account and submit beach updates.</p><Link href="/auth/login" className="mt-6 inline-block font-semibold text-primary underline-offset-4 hover:underline">Back to sign in</Link></section></main>
  return <main className="flex min-h-screen items-center justify-center bg-background px-5 py-12"><form onSubmit={submit} className="flex w-full max-w-md flex-col gap-5 rounded-3xl border border-border bg-card p-7 shadow-sm"><div><p className="eyebrow">Join the coast</p><h1 className="font-serif text-4xl font-bold">Create account</h1><p className="mt-2 text-sm text-muted-foreground">Your email keeps community updates accountable.</p></div>{error && <p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<label className="flex flex-col gap-2 text-sm font-semibold">Name<input required value={displayName} onChange={(e) => setDisplayName(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Password<input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><Button disabled={busy}>{busy ? 'Creating account…' : 'Create account'}</Button><p className="text-center text-sm text-muted-foreground">Already registered? <Link className="font-semibold text-primary underline-offset-4 hover:underline" href="/auth/login">Sign in</Link></p></form></main>
}
