'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Anchor, RadioTower, Check, Compass, Eye, Flag, Footprints, MapPin, Radar, Route, Sailboat, ShieldCheck, Trophy, Users, ClipboardList } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Badge = { id: string; track: 'explorer' | 'pulse'; name: string; threshold: number; icon: string; sort_order: number }
type RewardData = { badges: Badge[]; earned: { badge_id: string; earned_at: string }[]; explorerCount: number; pulseCount: number }
const icons: Record<string, React.ComponentType<{ className?: string }>> = { footprints: Footprints, anchor: Anchor, 'map-pin': MapPin, sailboat: Sailboat, compass: Compass, route: Route, flag: Flag, trophy: Trophy, broadcast: RadioTower, eye: Eye, 'clipboard-list': ClipboardList, users: Users, 'shield-check': ShieldCheck, 'radar-2': Radar }

function Track({ title, description, badges, count, earned }: { title: string; description: string; badges: Badge[]; count: number; earned: Set<string> }) {
  const next = badges.find((badge) => !earned.has(badge.id))
  return <div className="rounded-2xl border border-border bg-background p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Contribution track</p><h3 className="mt-1 font-serif text-2xl font-bold">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{description}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-sm font-bold">{count}</span></div>{next && <div className="mt-5"><div className="flex items-center justify-between text-xs font-semibold"><span>Next: {next.name}</span><span>{count} / {next.threshold}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, count / next.threshold * 100)}%` }} /></div></div>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{badges.map((badge) => { const Icon = icons[badge.icon] ?? Compass; const isEarned = earned.has(badge.id); return <div key={badge.id} className={`flex items-center gap-3 rounded-xl border p-3 ${isEarned ? 'border-primary/50 bg-primary/5' : 'border-border opacity-60'}`}><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-secondary"><Icon className={isEarned ? 'text-primary' : 'text-muted-foreground'} /></div><div className="min-w-0"><p className="font-semibold">{badge.name}</p><p className="text-xs text-muted-foreground">{badge.threshold} {title === 'Explorer' ? 'beaches' : 'updates'}</p></div>{isEarned && <Check className="ml-auto text-primary" />}</div> })}</div></div>
}

export function RewardsPanel() {
  const [user, setUser] = useState<{ email?: string } | null>(null); const [data, setData] = useState<RewardData | null>(null); const [error, setError] = useState('')
  useEffect(() => { const supabase = createClient(); supabase.auth.getUser().then(({ data: result }: { data: { user: { email?: string } | null } }) => { setUser(result.user); if (result.user) fetch('/api/rewards').then((response) => response.json()).then(setData).catch(() => setError('Rewards are temporarily unavailable.')) }); const { data: listener } = supabase.auth.onAuthStateChange((_event: any, session: any) => { setUser(session?.user ?? null); if (!session?.user) setData(null) }); return () => listener.subscription.unsubscribe() }, [])
  const earned = useMemo(() => new Set(data?.earned.map((item) => item.badge_id)), [data])
  return <section id="rewards" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="grid gap-6 p-6 lg:grid-cols-[0.7fr_1.3fr] lg:p-10"><div><img src="/abyssyaatra-badge-sheet.svg" alt="AbyssYaatra badge collection" className="mb-6 w-full max-w-sm rounded-2xl border border-border bg-secondary p-3" /><p className="eyebrow">Your contribution trail</p><h2 className="section-title">Every helpful update leaves a mark.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Earn badges for expanding the beach guide and keeping the community pulse fresh. Approved contributions count automatically.</p>{!user && <div className="mt-6 flex flex-wrap gap-3"><Link href="/auth/login" className="rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Sign in to see rewards</Link><Link href="/auth/sign-up" className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">Join the community</Link></div>}{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</div>{user && data && <div className="flex flex-col gap-5"><Track title="Explorer" description="Photograph distinct beaches and help travellers discover more of the coast." badges={data.badges.filter((badge) => badge.track === 'explorer')} count={data.explorerCount} earned={earned} /><Track title="Community pulse" description="Share on-the-ground status updates so travellers know what the shore feels like today." badges={data.badges.filter((badge) => badge.track === 'pulse')} count={data.pulseCount} earned={earned} /></div>}{user && !data && <div className="flex items-center justify-center rounded-2xl bg-secondary p-10 text-sm text-muted-foreground">Loading your contribution trail…</div>}</div></div></section>
}
