'use client'

import Link from 'next/link'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); const { error } = await createClient().auth.signInWithPassword({ email, password }); setBusy(false); if (error) setError(error.message.toLowerCase().includes('confirm') ? 'Please confirm your email before signing in.' : error.status === 429 ? 'Too many attempts. Please try again later.' : 'Invalid email or password.'); else window.location.href = '/' }
  return <main className="grid min-h-screen bg-background lg:grid-cols-[0.9fr_1.1fr]"><div className="relative hidden min-h-screen overflow-hidden lg:block"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-wlUTLBI01wbcktcpZnOa5QvTcmlVZl.png" alt="Rocky coastline at the edge of the sea" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-foreground/35"/><div className="absolute inset-x-0 bottom-0 p-12 text-primary-foreground"><p className="eyebrow text-primary-foreground/75">AbyssYaatra</p><h2 className="mt-3 max-w-md font-serif text-5xl font-bold leading-tight">Find the coast that feels like yours.</h2></div></div><div className="flex items-center justify-center px-5 py-12"><form onSubmit={submit} className="flex w-full max-w-md flex-col gap-5 rounded-3xl border border-border bg-card p-7 shadow-sm lg:p-9"><Link href="/" className="font-serif text-xl font-bold text-foreground">AbyssYaatra</Link><div><p className="eyebrow">AbyssYaatra account</p><h1 className="font-serif text-4xl font-bold">Welcome back</h1><p className="mt-2 text-sm text-muted-foreground">Sign in to share trusted beach updates.</p></div>{error && <p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<label className="flex flex-col gap-2 text-sm font-semibold">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Password<input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><Button disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</Button><p className="text-center text-sm text-muted-foreground">New here? <Link className="font-semibold text-primary underline-offset-4 hover:underline" href="/auth/sign-up">Create an account</Link></p></form></div></main>
}
